theme: jekyll-theme-slate
name: Bounded biharmonic blending of Möbius transformations for flexible omnidirectional image rectification
title: Bounded biharmonic blending of Möbius transformations for flexible omnidirectional image rectification
